FROM ubuntu

ENV TZ=Europe/Moscow 
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone 
RUN apt-get update && \
    apt-get install -y \
    qtcreator \
    qtbase5-dev \
    qt5-qmake \
    cmake \
    build-essential
 
WORKDIR /root/
RUN mkdir server
WORKDIR /root/server/
COPY *.cpp /root/server/
COPY *.h /root/server/
COPY *.pro /root/server/
COPY *.db /root/server/

RUN qmake echoServer.pro
RUN make 

ENTRYPOINT ["./echoServer"]
